version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://127.0.0.1:8000/api
    volumes:
      - .:/app
      - /app/node_modules
